#### Feature-pack build config file (wildfly-feature-pack-build.xml)

Feature-pack building starts with this file. The file describes the feature-pack in terms of its dependencies on other feature-packs, default packages, configs and other options such as from which artifact groups to extract schemas into the distribution's `docs/schema` directory.

If the file includes feature-pack dependencies, those feature-packs must be resolvable as Maven artifacts during the build process. They will be explored to collect the provisioning descriptions (such as feature-pack.xml, etc) of the dependencies.

Most of the content of this file is basically copied directly into the final `feature-pack.xml` generated by the mojo. Here is an excerpt from the WildFly Servlet feature-pack build config file

[source,xml]
----
<build xmlns="urn:wildfly:feature-pack-build:2.0">
    <dependencies>
        <dependency group-id="org.wildfly.core" artifact-id="wildfly-core-galleon-pack">
            <name>org.wildfly.core:wildfly-core-galleon-pack</name>
            <packages inherit="false">
                <exclude name="product.conf"/>
            </packages>
            <default-configs inherit="false"/>
        </dependency>
    </dependencies>
    <default-packages>
        <package name="modules.all"/>
        <package name="docs"/>
    </default-packages>
    <package-schemas>
        <group name="org.jboss.as"/>
        <group name="org.wildfly"/>
        <group name="org.wildfly.core"/>
    </package-schemas>
    <config model="standalone">
        <packages>
            <package name="product.conf" optional="true"/>
            <package name="misc.standalone"/>
        </packages>
    </config>
    <!-- the rest is skipped -->
----

All the elements in the above excerpt except for package-schemas are actual `feature-pack.xml` content that will be copied to the resulting feature-pack.xml as-is.

##### Extracting schemas

The presence of element `package-schemas` instructs the mojo to create a package called `docs.schema`. The package includes no content but a file with Maven artifact groupIds from which XSD schemas should be extracted into the distribution's docs/schema directory, in case `docs.schema` package was selected to be installed (it is by default).
