[[Feature-pack-build-config-file]]
### Feature-pack build config file (wildfly-feature-pack-build.xml)

Feature-pack building starts with this file. The file describes the feature-pack in terms of its dependencies on other
feature-packs, default packages, configs and other options such as from which artifact groups to extract schemas into
the distribution's `docs/schema` directory.

If the file includes feature-pack dependencies, those feature-packs must be resolvable as Maven artifacts during the
build process. They will be explored to collect the provisioning descriptions (such as feature-pack.xml, etc) of the
dependencies.

Normally, most of the content of this file will be copied directly into the final `feature-pack.xml` generated by the mojo.
Here is an example from WildFly Servlet feature-pack build config file

[source,xml]
----
<build xmlns="urn:wildfly:feature-pack-build:2.0">
    <dependencies>
        <dependency group-id="org.wildfly.core" artifact-id="wildfly-core-galleon-pack">
            <name>org.wildfly.core:wildfly-core-galleon-pack</name>
            <packages inherit="false">
                <exclude name="product.conf"/>
            </packages>
            <default-configs inherit="false"/>
        </dependency>
    </dependencies>
    <default-packages>
        <package name="modules.all"/>
        <package name="docs"/>
    </default-packages>
    <package-schemas>
        <group name="org.jboss.as"/>
        <group name="org.wildfly"/>
        <group name="org.wildfly.core"/>
    </package-schemas>
    <config model="standalone">
        <packages>
            <package name="product.conf" optional="true"/>
            <package name="misc.standalone"/>
        </packages>
    </config>

    <!-- other configs are skipped -->

    <generate-feature-specs>
        <extensions>
            <standalone>
                <extension>org.jboss.as.ee</extension>
                <extension>org.jboss.as.naming</extension>
                <extension>org.jboss.as.security</extension>
                <extension>org.wildfly.extension.undertow</extension>
            </standalone>
            <domain>
                <extension>org.jboss.as.ee</extension>
                <extension>org.jboss.as.naming</extension>
                <extension>org.jboss.as.security</extension>
                <extension>org.wildfly.extension.undertow</extension>
            </domain>
        </extensions>
    </generate-feature-specs>
</build>
----

All the elements in the above example except for package-schemas and `generate-feature-specs` are actual `feature-pack.xml` content that will be
copied to the resulting feature-pack.xml as-is.

##### Extracting schemas

The presence of element `package-schemas` instructs the mojo to create a package called `docs.schema`. The package
includes no content but a file with Maven artifact groupIds from which XSD schemas should be extracted into the
distribution's docs/schema directory, in case `docs.schema` package was selected to be installed (it is by default).

##### Feature specs generation

Feature-pack may or may not include feature specs (XML files describing configuration features). Feature specs are included only if the feature-pack includes one or more subsystems that should be added to the confuration when the feature-pack is installed.

In WildFly feature-packs, feature specs are generated. `generate-feature-specs` is an element that lists extensions included in the feature-pack for which feature specs should be generated.

IMPORTANT: feature specs are generated using `generate-feature-specs` goal of the plugin.

##### Adding provisioning plugins

Feature-packs that depend on WildFly (or WildFly Core), normally, don't need to add any provisioning plugins to be usable by Galleon. WildFly Core feature-pack includes the plugins that are used during provisioning for all the feature-packs that (directly or indirectly) depend on it. Here is a snipped from WildFly Core `wildfly-feature-pack-build.xml` that adds WildFly provisioning plugin JARs:

[source,xml]
----
<build xmlns="urn:wildfly:feature-pack-build:3.0" producer="wildfly-core@maven(org.jboss.universe:community-universe):current">
    <!-- content skipped -->

    <plugins>
        <plugin artifact="org.wildfly.galleon-plugins:wildfly-galleon-plugins"/> <!--1-->
    </plugins>

    <resources>
        <copy artifact="org.wildfly.galleon-plugins:wildfly-config-gen" to="wildfly/wildfly-config-gen.jar"/> <!--2-->
    </resources>

    <!-- content skipped -->
</build>
----
<1> `plugins` element may include multiple `plugin` elements specifying Maven artifact coordinates of the plugin
<2> `copy` element under `resources` instructs to copy the specified artifact to the feature-pack `resources` directory

NOTE: Both artifact coordinates above are missing versions. Although the versions could specified, in this case they will be resolved from the Maven project dependencies at the plugin execution time.
