### generate-feature-specs

This Maven mojo generates WildFly provisioning feature specs.

Feature spec is generated for every resource described in the management model (unless it is a runtime-only, proxy or a resource alias). Feature specs are also generated for OBJECT attributes (not recursively) and items of LISTs of complex values.

The mojo starts a minimal embedded server with the specified extensions in the configuration and invokes `read-feature-description` operation on the root resource. For some resources like subsystems, the results of `read-feature-description` for standalone and domain modes are merged into a single description and subsequently a single feature spec is generated for both modes.

The generated feature specs are later included into the feature-pack generated by <<_build_feature_pack>>

.Parameters
[%autowidth.stretch]
|====
|Parameter name |Required |Default |Description

|domain-extensions
|true
|-
|List of domain extensions for which feature specs should be generated

|host-extensions
|true
|-
|List of host extensions for which feature specs should be generated

|standalone-extensions
|true
|-
|List of standalone extensions for which feature specs should be generated

|external-artifacts
|false
|-
|List of external artifacts to be added to the embedded server classpath

|feature-packs
|false
|-
|Feature-packs artifacts the new feature-pack will depend on

|fork-embedded
|false
|false
|Whether to launch the embedded server to read feature descriptions in a separate process

|outputDirectory
|true
|-
|The directory where the generated specifications are written.

|====

.Sample plugin configuration
[source,xml]
----

<plugin>
  <groupId>org.wildfly.galleon-plugins</groupId>
  <artifactId>wildfly-galleon-maven-plugins</artifactId>
  <executions>
    <execution>
      <id>feature-spec-build</id>
      <goals>
        <goal>generate-feature-specs</goal>
      </goals>
      <phase>prepare-package</phase>
      <configuration>
        <output-dir>${basedir}/target/resources/features</output-dir>
        <feature-packs>
          <feature-pack>
            <groupId>org.wildfly.core</groupId>
            <artifactId>wildfly-core-galleon-pack</artifactId>
            <version>${version.org.wildfly.core}</version>
            <type>zip</type>
            <extension>zip</extension>
          </feature-pack>
          <feature-pack>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-servlet-galleon-pack</artifactId>
            <version>${project.version}</version>
            <type>zip</type>
            <extension>zip</extension>
          </feature-pack>
        </feature-packs>
        <external-artifacts>
          <external-artifact>
            <artifactItem>
              <groupId>org.apache.activemq</groupId>
              <artifactId>artemis-native</artifactId>
              <version>${version.org.apache.activemq.artemis}</version>
            </artifactItem>
            <includes>lib/**</includes>
            <excludes>*.*</excludes>
            <toLocation>system/layers/base/org/apache/activemq/artemis/journal/main</toLocation>
          </external-artifact>
        </external-artifacts>
        <standalone-extensions>
          <extension>org.wildfly.extension.discovery</extension>
          <extension>org.jboss.as.clustering.infinispan</extension>
          <extension>org.jboss.as.clustering.jgroups</extension>
          <!-- skipped content -->
          <extension>org.wildfly.extension.undertow</extension>
          <extension>org.wildfly.iiop-openjdk</extension>
        </standalone-extensions>
        <domain-extensions>
          <extension>org.wildfly.extension.discovery</extension>
          <extension>org.jboss.as.clustering.infinispan</extension>
         <!-- skipped content -->
          <extension>org.wildfly.extension.undertow</extension>
          <extension>org.wildfly.iiop-openjdk</extension>
        </domain-extensions>
        <host-extensions>
          <extension>org.jboss.as.jmx</extension>
          <extension>org.wildfly.extension.core-management</extension>
          <extension>org.wildfly.extension.discovery</extension>
          <extension>org.wildfly.extension.elytron</extension>
        </host-extensions>
      </configuration>
    </execution>
  </executions>
</plugin>

----
