include::../../../../../maven-plugin/target/generated-sources/plugin/generate-feature-specs-mojo.adoc[]

#### Sample Configuration

.Sample plugin configuration
[source,xml]
----

<plugin>
  <groupId>org.wildfly.galleon-plugins</groupId>
  <artifactId>wildfly-galleon-maven-plugin</artifactId>
  <executions>
    <execution>
      <id>feature-spec-build</id>
      <goals>
        <goal>generate-feature-specs</goal>
      </goals>
      <phase>prepare-package</phase>
      <configuration>
        <output-dir>${basedir}/target/resources/features</output-dir> <--1-->
      </configuration>
    </execution>
  </executions>
</plugin>

----

<1> output-Dir: The directory where the generated specifications are written.

#### How it works

This section explains the basic mechanism of feature spec generation in WildFly.

Since the whole mechanism relies on the WildFly metamodel, we create a mininal configuration file with all the extensions we want to be able to configure in the feature-pack. Then we boot the embedded server and execute `read-feature-description(recursive)` management operation on the root resource. The operation returns the description of Galleon feature spec for every resource in the model that may appear in server configurations.

Each resource registration in the WildFly model is considered to be a feature as long as it is not a `proxy`, a
`runtime only` or an `alias`. The registration address is used to define the feature-id of the feature and all
attributes that can be used in the `add` operation handler will become parameters.

Capabilities are used to define the links between feature specs thus defining how the operations will be grouped, ordered and executed.

Complex attributes are represented as usual feature parameters and also as separate feature specs. Which means complex attribute values can be configured using Galleon features. Dependending on the actual parameter type, features that represent complex attribute values will be added to the configuration using `write-attribute` or `list-add` operations instead of `add`.

Certain feature specs for *standalone* server, *domain* and *host* controller are processed and merged
into a single feature spec (if no incompatibility exists between those three models) to have a single feature spec re-usable in the three configuration models.
